import type { MarketplaceState } from "@/domain/entities"

const now = Date.now()
const hoursAgo = (hours: number) => new Date(now - hours * 60 * 60 * 1000).toISOString()
const hoursFromNow = (hours: number) => new Date(now + hours * 60 * 60 * 1000).toISOString()

export const PLATFORM_FEE_RATE = 0.12

export function createSeedState(): MarketplaceState {
  return {
    currentUserId: "user_ana",
    activeNeighborhoodId: "nbh_pinheiros",
    neighborhoods: [
      {
        id: "nbh_pinheiros",
        name: "Pinheiros",
        city: "São Paulo",
        location: { lat: -23.5674, lng: -46.6934 },
      },
      {
        id: "nbh_vila_madalena",
        name: "Vila Madalena",
        city: "São Paulo",
        location: { lat: -23.5533, lng: -46.6908 },
      },
      {
        id: "nbh_jardins",
        name: "Jardins",
        city: "São Paulo",
        location: { lat: -23.5681, lng: -46.6701 },
      },
      {
        id: "nbh_moema",
        name: "Moema",
        city: "São Paulo",
        location: { lat: -23.6015, lng: -46.6658 },
      },
      {
        id: "nbh_lapa",
        name: "Lapa",
        city: "São Paulo",
        location: { lat: -23.5216, lng: -46.7044 },
      },
    ],
    categories: [
      {
        id: "cat_ac",
        slug: "ar-condicionado",
        name: "Ar-condicionado",
        description: "Instalação, limpeza e reparo de splits e janela.",
        icon: "snowflake",
      },
      {
        id: "cat_eletrica",
        slug: "eletrica",
        name: "Elétrica",
        description: "Quadros, tomadas, iluminação e urgências.",
        icon: "zap",
      },
      {
        id: "cat_hidraulica",
        slug: "hidraulica",
        name: "Hidráulica",
        description: "Vazamentos, entupimentos e instalações.",
        icon: "droplets",
      },
      {
        id: "cat_faxina",
        slug: "faxina",
        name: "Faxina",
        description: "Limpeza residencial, pós-obra e recorrente.",
        icon: "sparkles",
      },
      {
        id: "cat_jardinagem",
        slug: "jardinagem",
        name: "Jardinagem",
        description: "Poda, paisagismo e manutenção de áreas verdes.",
        icon: "leaf",
      },
      {
        id: "cat_frete",
        slug: "frete-mudanca",
        name: "Frete e mudança",
        description: "Carreto, ajuda na carga e mudanças curtas.",
        icon: "truck",
      },
      {
        id: "cat_montagem",
        slug: "montagem",
        name: "Montagem de móveis",
        description: "Armários, camas e eletrodomésticos.",
        icon: "wrench",
      },
      {
        id: "cat_pintura",
        slug: "pintura",
        name: "Pintura",
        description: "Paredes internas, fachadas e retoques.",
        icon: "paintbrush",
      },
    ],
    users: [
      {
        id: "user_ana",
        name: "Ana Ribeiro",
        email: "ana@vizinho.app",
        phone: "(11) 98821-4410",
        role: "CLIENT",
        initials: "AR",
        accent: "#0f6e63",
      },
      {
        id: "user_bruno",
        name: "Bruno Lima",
        email: "bruno@vizinho.app",
        phone: "(11) 99712-8832",
        role: "CLIENT",
        initials: "BL",
        accent: "#3f5b4a",
      },
      {
        id: "user_ricardo",
        name: "Ricardo Alves",
        email: "ricardo@vizinho.app",
        phone: "(11) 97654-2201",
        role: "PROVIDER",
        initials: "RA",
        accent: "#1d6b8a",
      },
      {
        id: "user_diego",
        name: "Diego Rocha",
        email: "diego@vizinho.app",
        phone: "(11) 98110-3344",
        role: "PROVIDER",
        initials: "DR",
        accent: "#2f6f8f",
      },
      {
        id: "user_marina",
        name: "Marina Costa",
        email: "marina@vizinho.app",
        phone: "(11) 99200-1188",
        role: "PROVIDER",
        initials: "MC",
        accent: "#7a4b2a",
      },
      {
        id: "user_joao",
        name: "João Pedro Santos",
        email: "joao@vizinho.app",
        phone: "(11) 98440-7721",
        role: "PROVIDER",
        initials: "JS",
        accent: "#3d4a2f",
      },
      {
        id: "user_helena",
        name: "Helena Dias",
        email: "helena@vizinho.app",
        phone: "(11) 99551-0092",
        role: "PROVIDER",
        initials: "HD",
        accent: "#2f6a3a",
      },
      {
        id: "user_carlos",
        name: "Carlos Mendes",
        email: "carlos@vizinho.app",
        phone: "(11) 97331-5508",
        role: "PROVIDER",
        initials: "CM",
        accent: "#8a6a1d",
      },
      {
        id: "user_luciana",
        name: "Luciana Prado",
        email: "luciana@vizinho.app",
        phone: "(11) 98662-4419",
        role: "PROVIDER",
        initials: "LP",
        accent: "#1f5f7a",
      },
      {
        id: "user_thiago",
        name: "Thiago Nunes",
        email: "thiago@vizinho.app",
        phone: "(11) 99118-2260",
        role: "PROVIDER",
        initials: "TN",
        accent: "#5a4632",
      },
      {
        id: "user_fernanda",
        name: "Fernanda Oliveira",
        email: "fernanda@vizinho.app",
        phone: "(11) 98877-3340",
        role: "PROVIDER",
        initials: "FO",
        accent: "#6b3a4a",
      },
      {
        id: "user_admin",
        name: "Equipe Vizinho",
        email: "moderacao@vizinho.app",
        phone: "(11) 3000-1000",
        role: "ADMIN",
        initials: "VZ",
        accent: "#163a34",
      },
    ],
    clients: [
      {
        userId: "user_ana",
        address: "Rua dos Pinheiros, 1480 · apto 72",
        neighborhood: "Pinheiros",
        city: "São Paulo",
        location: { lat: -23.5674, lng: -46.6934 },
      },
      {
        userId: "user_bruno",
        address: "Rua Harmonia, 320",
        neighborhood: "Vila Madalena",
        city: "São Paulo",
        location: { lat: -23.5538, lng: -46.6912 },
      },
    ],
    providers: [
      {
        userId: "user_ricardo",
        bio: "Técnico em refrigeração há 11 anos. Atendo instalação, gás e manutenção de splits residenciais no mesmo dia.",
        radiusKm: 8,
        location: { lat: -23.5531, lng: -46.6919 },
        neighborhood: "Vila Madalena",
        verificationStatus: "APPROVED",
        ratingAvg: 4.9,
        ratingCount: 86,
        completedJobs: 214,
        yearsExperience: 11,
        startingPriceCents: 18000,
        specialtyCategoryIds: ["cat_ac"],
      },
      {
        userId: "user_diego",
        bio: "Instalo e faço limpeza de ar-condicionado com garantia de 90 dias. Orçamento após fotos do ambiente.",
        radiusKm: 12,
        location: { lat: -23.5578, lng: -46.6609 },
        neighborhood: "Consolação",
        verificationStatus: "APPROVED",
        ratingAvg: 4.6,
        ratingCount: 41,
        completedJobs: 98,
        yearsExperience: 6,
        startingPriceCents: 15000,
        specialtyCategoryIds: ["cat_ac"],
      },
      {
        userId: "user_marina",
        bio: "Faxina detalhada, com produtos próprios e rotina combinada. Trabalho sozinha ou em dupla para pós-obra.",
        radiusKm: 6,
        location: { lat: -23.5658, lng: -46.6881 },
        neighborhood: "Pinheiros",
        verificationStatus: "APPROVED",
        ratingAvg: 4.8,
        ratingCount: 124,
        completedJobs: 310,
        yearsExperience: 8,
        startingPriceCents: 16000,
        specialtyCategoryIds: ["cat_faxina"],
      },
      {
        userId: "user_joao",
        bio: "HR e baú para mudanças curtas. Cuidado com móveis, montagem básica e duas ajudas na equipe.",
        radiusKm: 15,
        location: { lat: -23.5284, lng: -46.7021 },
        neighborhood: "Lapa",
        verificationStatus: "APPROVED",
        ratingAvg: 4.7,
        ratingCount: 67,
        completedJobs: 151,
        yearsExperience: 9,
        startingPriceCents: 22000,
        specialtyCategoryIds: ["cat_frete", "cat_montagem"],
      },
      {
        userId: "user_helena",
        bio: "Paisagista com foco em varandas e quintais compactos. Poda, adubação e irrigação simples.",
        radiusKm: 10,
        location: { lat: -23.5719, lng: -46.7094 },
        neighborhood: "Butantã",
        verificationStatus: "APPROVED",
        ratingAvg: 5.0,
        ratingCount: 38,
        completedJobs: 72,
        yearsExperience: 7,
        startingPriceCents: 14000,
        specialtyCategoryIds: ["cat_jardinagem"],
      },
      {
        userId: "user_carlos",
        bio: "Eletricista residencial. Troca de disjuntores, chuveiro e iluminação. Documentação em análise.",
        radiusKm: 9,
        location: { lat: -23.5662, lng: -46.6688 },
        neighborhood: "Jardins",
        verificationStatus: "PENDING",
        ratingAvg: 4.5,
        ratingCount: 19,
        completedJobs: 44,
        yearsExperience: 5,
        startingPriceCents: 12000,
        specialtyCategoryIds: ["cat_eletrica"],
      },
      {
        userId: "user_luciana",
        bio: "Encanadora. Desentupimento sem quebrar piso sempre que possível e troca de registros.",
        radiusKm: 8,
        location: { lat: -23.5328, lng: -46.7362 },
        neighborhood: "Vila Leopoldina",
        verificationStatus: "APPROVED",
        ratingAvg: 4.8,
        ratingCount: 53,
        completedJobs: 129,
        yearsExperience: 10,
        startingPriceCents: 13000,
        specialtyCategoryIds: ["cat_hidraulica"],
      },
      {
        userId: "user_thiago",
        bio: "Montador de móveis planejados e de loja. Levo ferramentas e organizo a sucata para descarte.",
        radiusKm: 11,
        location: { lat: -23.5992, lng: -46.6669 },
        neighborhood: "Moema",
        verificationStatus: "APPROVED",
        ratingAvg: 4.5,
        ratingCount: 29,
        completedJobs: 81,
        yearsExperience: 4,
        startingPriceCents: 11000,
        specialtyCategoryIds: ["cat_montagem"],
      },
      {
        userId: "user_fernanda",
        bio: "Pintura interna com tinta de baixo odor. Protejo piso e rodapé; deixo o ambiente ventilado.",
        radiusKm: 7,
        location: { lat: -23.5369, lng: -46.6788 },
        neighborhood: "Perdizes",
        verificationStatus: "APPROVED",
        ratingAvg: 4.9,
        ratingCount: 47,
        completedJobs: 103,
        yearsExperience: 8,
        startingPriceCents: 25000,
        specialtyCategoryIds: ["cat_pintura"],
      },
    ],
    requests: [
      {
        id: "req_split_ana",
        clientId: "user_ana",
        categoryId: "cat_ac",
        title: "Split do quarto pingando na parede",
        description:
          "Split 9 mil BTUs no quarto. Desde ontem pinga na parede e o ar sai morno. Mando foto da condensadora na varanda.",
        attachments: ["condensadora-varanda.jpg", "parede-mancha.jpg"],
        address: "Rua dos Pinheiros, 1480 · apto 72",
        location: { lat: -23.5674, lng: -46.6934 },
        scheduleType: "IMMEDIATE",
        scheduledAt: null,
        preferredProviderId: null,
        status: "PROPOSALS_RECEIVED",
        createdAt: hoursAgo(5),
      },
      {
        id: "req_faxina_ana",
        clientId: "user_ana",
        categoryId: "cat_faxina",
        title: "Faxina pesada do apto 72 m²",
        description:
          "Apartamento de 2 quartos após reforma da cozinha. Fogão, armários e banheiros precisam de atenção extra.",
        attachments: ["cozinha-pos-obra.jpg"],
        address: "Rua dos Pinheiros, 1480 · apto 72",
        location: { lat: -23.5674, lng: -46.6934 },
        scheduleType: "SCHEDULED",
        scheduledAt: hoursFromNow(4),
        preferredProviderId: "user_marina",
        status: "IN_PROGRESS",
        createdAt: hoursAgo(28),
      },
      {
        id: "req_frete_bruno",
        clientId: "user_bruno",
        categoryId: "cat_frete",
        title: "Mudança de kitnet para Pinheiros",
        description:
          "Sofá, cama e 18 caixas. Prédio com elevador na origem e na chegada.",
        attachments: ["sofa.jpg"],
        address: "Rua Harmonia, 320",
        location: { lat: -23.5538, lng: -46.6912 },
        scheduleType: "SCHEDULED",
        scheduledAt: hoursAgo(30),
        preferredProviderId: "user_joao",
        status: "COMPLETED",
        createdAt: hoursAgo(96),
      },
    ],
    proposals: [
      {
        id: "prop_ricardo_split",
        requestId: "req_split_ana",
        providerId: "user_ricardo",
        amountCents: 28000,
        etaHours: 2,
        message:
          "Provavelmente é drenagem entupida e gás baixo. Levo bomba, nitrogênio e carga se precisar. Consigo ir hoje ainda.",
        status: "PENDING",
        createdAt: hoursAgo(3),
      },
      {
        id: "prop_diego_split",
        requestId: "req_split_ana",
        providerId: "user_diego",
        amountCents: 22000,
        etaHours: 4,
        message:
          "Faço a limpeza completa e verifico o dreno. Se precisar de peça, aviso antes de cobrar qualquer extra.",
        status: "PENDING",
        createdAt: hoursAgo(2),
      },
      {
        id: "prop_marina_faxina",
        requestId: "req_faxina_ana",
        providerId: "user_marina",
        amountCents: 26000,
        etaHours: 5,
        message:
          "Vou com produto desengordurante e dupla se o pós-obra estiver pesado. Começo às 14h.",
        status: "ACCEPTED",
        createdAt: hoursAgo(26),
      },
      {
        id: "prop_joao_frete",
        requestId: "req_frete_bruno",
        providerId: "user_joao",
        amountCents: 48000,
        etaHours: 3,
        message: "HR + 2 ajudantes. Cobertores e cintas inclusos.",
        status: "ACCEPTED",
        createdAt: hoursAgo(90),
      },
    ],
    jobs: [
      {
        id: "job_faxina_ana",
        requestId: "req_faxina_ana",
        proposalId: "prop_marina_faxina",
        clientId: "user_ana",
        providerId: "user_marina",
        status: "IN_PROGRESS",
        scheduledAt: hoursFromNow(4),
        startedAt: hoursAgo(1),
        completedAt: null,
      },
      {
        id: "job_frete_bruno",
        requestId: "req_frete_bruno",
        proposalId: "prop_joao_frete",
        clientId: "user_bruno",
        providerId: "user_joao",
        status: "COMPLETED",
        scheduledAt: hoursAgo(30),
        startedAt: hoursAgo(32),
        completedAt: hoursAgo(28),
      },
    ],
    payments: [
      {
        id: "pay_faxina_ana",
        jobId: "job_faxina_ana",
        amountCents: 26000,
        platformFeeCents: 3120,
        providerAmountCents: 22880,
        status: "HELD",
        createdAt: hoursAgo(24),
        releasedAt: null,
      },
      {
        id: "pay_frete_bruno",
        jobId: "job_frete_bruno",
        amountCents: 48000,
        platformFeeCents: 5760,
        providerAmountCents: 42240,
        status: "RELEASED",
        createdAt: hoursAgo(90),
        releasedAt: hoursAgo(28),
      },
    ],
    messages: [
      {
        id: "msg_1",
        requestId: "req_split_ana",
        senderId: "user_ana",
        type: "TEXT",
        body: "O split começou a pingar ontem à noite. Tem foto da condensadora na varanda.",
        createdAt: hoursAgo(5),
      },
      {
        id: "msg_2",
        requestId: "req_split_ana",
        senderId: "user_ricardo",
        type: "TEXT",
        body: "Vi as fotos. O dreno parece entupido e o ar morno indica gás. Consigo ir hoje, em cerca de 2 horas.",
        createdAt: hoursAgo(3),
      },
      {
        id: "msg_3",
        requestId: "req_split_ana",
        senderId: "user_diego",
        type: "TEXT",
        body: "Posso encaixar no fim da tarde. O valor já inclui limpeza das serpentinas.",
        createdAt: hoursAgo(2),
      },
      {
        id: "msg_4",
        requestId: "req_faxina_ana",
        senderId: "user_marina",
        type: "SYSTEM",
        body: "Marina saiu para o atendimento. O pagamento permanece retido até você confirmar o serviço.",
        createdAt: hoursAgo(1),
      },
      {
        id: "msg_5",
        requestId: "req_faxina_ana",
        senderId: "user_marina",
        type: "TEXT",
        body: "Cheguei. Vou começar pela cozinha e te aviso se precisar de mais tempo no pós-obra.",
        createdAt: hoursAgo(1),
      },
      {
        id: "msg_6",
        requestId: "req_frete_bruno",
        senderId: "user_joao",
        type: "SYSTEM",
        body: "Serviço concluído. O repasse de R$ 422,40 foi liberado para João Pedro.",
        createdAt: hoursAgo(28),
      },
    ],
    reviews: [
      {
        id: "rev_bruno_joao",
        jobId: "job_frete_bruno",
        fromUserId: "user_bruno",
        toUserId: "user_joao",
        rating: 5,
        comment: "Pontual, protegeu o sofá e não teve surpresa no preço.",
        createdAt: hoursAgo(27),
      },
      {
        id: "rev_joao_bruno",
        jobId: "job_frete_bruno",
        fromUserId: "user_joao",
        toUserId: "user_bruno",
        rating: 5,
        comment: "Acesso fácil, cliente organizado com as caixas. Recomendo.",
        createdAt: hoursAgo(27),
      },
      {
        id: "rev_extra_ricardo",
        jobId: "job_frete_bruno",
        fromUserId: "user_bruno",
        toUserId: "user_ricardo",
        rating: 5,
        comment: "Instalou o split da sala no mesmo dia, sem sujeira.",
        createdAt: hoursAgo(240),
      },
    ],
    documents: [
      {
        id: "doc_carlos_rg",
        providerId: "user_carlos",
        type: "RG",
        fileName: "rg-carlos-mendes.pdf",
        status: "PENDING",
        submittedAt: hoursAgo(18),
        notes: null,
      },
      {
        id: "doc_carlos_mei",
        providerId: "user_carlos",
        type: "MEI",
        fileName: "certidao-mei.pdf",
        status: "PENDING",
        submittedAt: hoursAgo(18),
        notes: null,
      },
      {
        id: "doc_ricardo_cnh",
        providerId: "user_ricardo",
        type: "CNH",
        fileName: "cnh-ricardo.pdf",
        status: "APPROVED",
        submittedAt: hoursAgo(800),
        notes: null,
      },
    ],
  }
}
